logging:
  config: classpath:log4j2-dev.xml

spring:
  boot:
    admin:
      client:
        prefer-ip: true
      url: http://localhost/app-admin
  sleuth:
    #总开关
    enabled: false
    sampler:
      #采样比率,1所有请求都trace,0.1百分之十的请求会trace
      percentage: 1
    scheduled:
      enabled: false
    async:
      enabled: false
      configurer:
        enabled: false
    integration:
      enabled: false
    zuul:
      enabled: false
    web:
      #http 接收请求开关
      enabled: true
      #接收的那些请求不会trace,注意是正则
      skip-pattern: /sbm/.*|/v2/api-docs.*|/api-docs.*|/error.*|/swagger.*|.*\.png|.*\.gif|.*\.jpg|.*\.css|.*\.js|.*\.html|/favicon.ico|/hystrix.stream|.*\.woff
      client:
        #http 调用请求开关
        enabled: true
        #发出去的那些请求不会trace,注意是以prefix开始的uri,中间用,分隔
        skip-uri-prefix: /app-admin
  zipkin:
    enabled: true
    kafka:
      topic: topic-srvMonitor
    sender:
      type: kafka
  kafka:
    bootstrapServers: 172.16.170.70:9092,172.16.170.71:9092,172.16.170.72:9092

druid:
  initialSize: 1
  minIdle: 1
  maxActive: 20
  maxWait: 3000
  useUnfairLock: true
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  poolPreparedStatements: false
  maxPoolPreparedStatementPerConnectionSize: 50
  validationQuery: SELECT 1
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false

dataSource:
  testDbMaster:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbtest1?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false
    username:
    password:

redis:
  key:
    prefix: ${spring.application.name}
    maxLength: 80
  hostName: 172.16.170.70
  password:
  defaultDbIndex: 0
  port: 6379
  timeout: 1000
  pool:
    maxIdel: 100
    maxTotal: 200
    minIdel: 10
    maxWaitMillis: 2000

elasticsearch:
  cluster-name: es-local
  cluster-nodes: 127.0.0.1:9200

elasticJob:
  #分布式job总开关
  enabled: false
  registryCenter:
    zkHost: localhost:2181
    namespace: demo-job
  demoJobConfig:
    enabled: false
    #定时任务运行的cron表达式
    cron: 0/30 * * * * ?
    #分片总数,即线程数(所有机器加起来的),越大并行度越高
    shardingTotalCount: 1
